name: hotcoco
channels:
  - conda-forge
  - defaults
dependencies:
- python=3.10
- matplotlib
- numpy
- cvxopt
- gym
- pyyaml
- pip
- pip:
    - ray[default]
    - tensorflow
    - PettingZoo
    - pettingzoo[butterfly]
    - opencv-python
